### PR TITLE
[SC Vote Required] Expansion of GH wishlist channel scope

### PR DESCRIPTION
**Pull request by anajsana**
Create new resolution in proposals folder related to the expansion of GitHub wishlist channel scope and change of name for SC to cast their vote

## Instructions:

Steering Committee Members should cast their vote by making edits on the line where their name appears. If needed, members can leave comments regarding their final vote in the Rationale section by adding their initials. As an alternative, members can leave a comment with their vote on this PR conversation page, and @anajsana will update the document accordingly.

```
- Annania Melaku - decline
- Ashley Wolf - abstain
- Brittany Istenes - absent
- Georg Kunz - abstain
- Leslie Hawthorn - absent
- Nik Peters - abstain
- Stephen Augustus - decline

### CODE REVIEW

**Comment by ashleywolf** [comment]
abstain

**Comment by hyandell** [comment]
This would be pointless. It's not a channel for "I wish that this service, or some service, offered something", it's a channel that GitHub were listening to. If GitLab wanted a channel, that could be setup, and the same for any other service.

**Comment by justaugustus** [comment]
To @hyandell's point and to explain my `against` vote, I believe that the channel exists to provide a focused forum for GitHub employees to be able to review. The value is diminished when you generalize the channel purpose.

That said, a few questions we should try to answer as follow-ups:
1. Is this providing value to the Hubbers that have access to the channel?
2. What is the scope of vendors allowed to ask for this type of forum within the TODO Group?

**Comment by gkunz** [comment]
I would appreciate to have a copy of the conversation which is referenced in the resolution either in this issue or in the resolution itself for context. Currently, I feel don't have enough context - also based on the fact that I was not a member of this channel up until now.

> That said, a few questions we should try to answer as follow-ups:
>     1. Is this providing value to the Hubbers that have access to the channel? 
>     2. What is the scope of vendors allowed to ask for this type of forum within the TODO Group?

I agree with this.

**Comment by annania** [comment]
> To @hyandell's point and to explain my `against` vote, I believe that the channel exists to provide a focused forum for GitHub employees to be able to review. The value is diminished when you generalize the channel purpose.
> 
> That said, a few questions we should try to answer as follow-ups:
> 
> 1. Is this providing value to the Hubbers that have access to the channel?
> 2. What is the scope of vendors allowed to ask for this type of forum within the TODO Group?

I agree with Stephen's comment - expanding the channel purpose diminishes value. As far as (Q2) I want to ensure that this does not signify an open invitation for all vendors to seek channels. GitHub holds a prominent position in open source and is a key platform for community participation. GitLab as well. Where do we draw the line for vendors?

**Comment by nikpete** [comment]
abstain and agree with Stephen's comment.

**Comment by anajsana** [comment]
Since 4 votes in favor are needed to pass the threshold (51%) and there are only 2 people who haven’t voted, it is impossible to reach the threshold of 4 votes in favor with only 2 remaining votes.

This resolution will be declined and GH wishlist will keep as it is

**Review by justaugustus — APPROVED** [review]
Approving the update to the content (to reflect Steering's vote to decline) and canceling the vote.

/cancel-vote

**Comment by lhawthorn** [comment]
I am sorry I missed this vote and will be more diligent to keep up on requests in the future.

**Pull request merged**
