### PR TITLE
Add OSPO Definition for formal approval

### PR DESCRIPTION
**Pull request by caniszczyk**
Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

### CODE REVIEW

**Comment by caniszczyk** [comment]
+1 from me

**Comment by decause** [comment]
+1

**Comment by stmcginnis** [comment]
+1 as a spectator.

**Comment by caniszczyk** [comment]
approved in today's SC meeting on 7/14/2020, thanks all!

**Pull request merged**
