### PR TITLE
Add structure for Steering Committee resolutions

### PR DESCRIPTION
**Pull request by kpfleming**
This patch adds a lightweight structure and process for the Steering
Committee to accept proposed actions from the members, act on them,
and record the results of those actions.

Signed-off-by: Kevin P. Fleming <kevin@km6g.us>

### CODE REVIEW

**Comment by jeffmcaffer** [comment]
Thanks Kevin for bringing some rigor to this space. Overall I'm fine with the approach. A question that came to mind was "could we use issues/PRs directly as the proposal/tracking mechanism?". Iin that approach, TODO members would open an issue or PR as appropriate and add a "proposal" label. SC votes would be through 👍 or 👎  on the OP. The outcome would be summarized in a final comment and the issue/PR closed/merged.

**Comment by kpfleming** [comment]
If we did that, the history of the process would not be fully represented in the repository, but would require a copy of the GitHub data around the repository.

**Comment by kpfleming** [comment]
This PR has been updated with the results of yesterday's SC meeting and is ready for merging.

**Comment by vmbrasseur** [comment]
We've already discussed this (months ago). I've reviewed the docs and see no problems.

SC members, please give a thumbs up/thumbs down to make this official. Paging @jeffmcaffer @DuaneOBrien @gyehuda @decause @ashleywolf to the white courtesy phone.

**Comment by caniszczyk** [comment]
LGTM

**Pull request merged**
