### PR TITLE
proposal: Refine Steering Committee selection criteria and election process

### PR DESCRIPTION
**Pull request by justaugustus**
Continues https://github.com/todogroup/governance/pull/90, with the intention of merging the initial proposal modulo actual changes to the charter.

Once this is merged, I will start incorporating feedback from https://github.com/todogroup/governance/issues/150.

### CODE REVIEW

**Comment by justaugustus** [comment]
@todogroup/steering-committee -- I've done some git surgery here (with attribution) to bring https://github.com/todogroup/governance/pull/90 back to a `proposed` state.

This PR **does NOT** actuate any changes on the charter; opting instead to list the changes as a diff within the proposal text.
My gentle suggestion is that we merge this ASAP to capture the intent and then follow-up with more PRs to incorporate feedback from https://github.com/todogroup/governance/issues/150.

**Comment by anajsana** [comment]
> @todogroup/steering-committee -- I've done some git surgery here (with attribution) to bring #90 back to a `proposed` state.
> 
> This PR **does NOT** actuate any changes on the charter; opting instead to list the changes as a diff within the proposal text. My gentle suggestion is that we merge this ASAP to capture the intent and then follow-up with more PRs to incorporate feedback from #150.

If I understood well, this PR only highlights the portion of text that needs to be changed based on issue #90, to keep track of it?

**Comment by justaugustus** [comment]
> @justaugustus If I understood well, this PR only highlights the portion of text that needs to be changed based on issue #90, to keep track of it?

Exactly! A change to the charter would only be allowed with a two-thirds majority vote of the SC, so instead of changing the charter, I'm just capturing the diff (so it can be reflected in the charter once the resolution is formally approved).

**Comment by justaugustus** [comment]
@todogroup/steering-committee -- I'm going to merge this, as it was partially approved by the previous SC. Again, no changes are made to the charter; just proposed.

I'll follow-up with updates to the proposal to incorporate feedback from https://github.com/todogroup/governance/issues/150.

**Pull request merged**
