### PR TITLE
[SC Vote Required] OSPO Associate Request

### PR DESCRIPTION
**Pull request by anajsana**
Create new resolution in proposals folder related to NEW OSPO Associate request submitted by FOSSA for SC to review and cast their vote

## Instructions:

Steering Committee Members should cast their vote by reacting to the git-vote comment below. If needed, members can leave a comment with their vote on this PR conversation page.

```
- Annania Melaku - {decline}
- Ashley Wolf - {decline}
- Brittany Istenes - {decline}
- Georg Kunz - {absent}
- Leslie Hawthorn - {decline}
- Nik Peters - {decline}
- Stephen Augustus - {decline}
```

### CODE REVIEW

**Comment by lhawthorn** [comment]
Voted.

**Comment by justaugustus** [comment]
Quoting https://todogroup.org/about/associates/:

> Entities who can apply for OSPO Associate include:
>
> - Open Source Communities and or projects
> - Academia
> - Governments
> - Non-governmental organizations (NGOs)
> - Non-profit Organizations (NPO)
>
> The OSPO Associates program is not intended for service providers. Individuals can always join the community and access our resources, following TODO’s code of conduct.

Resolution should be updated to reflect the above context.

The vote is currently at 4 against, effectively denying this request.

**Comment by anajsana** [comment]
Thanks, SC for casting your votes! With 6 votes against and 1 absent, the resolution is declined.

**Pull request merged**
