### PR TITLE
Create proposals issue form

### PR DESCRIPTION
**Pull request by anajsana**
This proposal form is related to the issue https://github.com/todogroup/governance/issues/111

### CODE REVIEW

**Comment by geekygirldawn** [comment]
I think we need some additional text at the top to give people some guidance about what types of proposals need to go in front of the SC. For example, a proposal for a new guide, case study, or tool would go elsewhere and not need to go to the SC. Wouldn't this be limited to new initiatives or new programs that would be driven by the TODO Group, while any proposal related to an existing program or initiative would

**Comment by geekygirldawn** [comment]
Oops, accidentally closed this while commenting.

**Review by justaugustus — COMMENTED** [review]
This may warrant further discussion. I've added it to next week's agenda.
ref: https://github.com/todogroup/governance/issues/111#issuecomment-1005698642

**Comment by anajsana** [comment]
> I think we need some additional text at the top to give people some guidance about what types of proposals need to go in front of the SC. For example, a proposal for a new guide, case study, or tool would go elsewhere and not need to go to the SC. Wouldn't this be limited to new initiatives or new programs that would be driven by the TODO Group, while any proposal related to an existing program or initiative would be a regular in the repo already existing for that program or initiative?

That's a good point @geekygirldawn. Indeed, this form is only for new proposals (that's why I added the last checkbox, but I understand that this is not clear enough, so I'll edit the description a bit). I would say that if the community wants to propose a new guide or use case, those forms should be created under todogorup.org repo, since both resources will be published in the website and they are both initiatives that already exist and don't need to be approved by the SC.

**Comment by vmbrasseur** [comment]
I've been out of the SC game for a year and need some context on this. Clarification as Dawn requested above may help with that context, but in general I'm not sure of the purpose of this? What exactly is a "proposal" here? Do we have supporting documentation around this concept and the process that proposals will go through?

**Comment by anajsana** [comment]
> I've been out of the SC game for a year and need some context on this. Clarification as Dawn requested above may help with that context, but in general, I'm not sure of the purpose of this? What exactly is a "proposal" here? Do we have supporting documentation around this concept and the process that proposals will go through?

@vmbrasseur this was something that came through our SC meeting discussions about how people from the community can better communicate with the SC and propose a new initiative that is not part of the approved TODO strategic goals in a more formal way where the community can easily interact (e.g explain the goal, main purpose, why this benefits the OSPO ecosystem, etc). For instance, if someone from TODO wants to see TODO joining OSPO Alliance or vice versa, that person can file a proposal form with a clear purpose documented. (Please @geekygirldawn correct me if I'm wrong here).

There is no written documentation made, just a rough idea from previous meetings. But something the SC can discuss in this issue.

On the other hand and IMHO, I'd say this kind of form shouldn't be limited to this "proposal" issue that is more related with SC activities, but also have multiple issue forms for each of the current TODO initiatives across the repos. For instance: 

* **[Done] Submit a CFP for OSPOlogy** | ospology repo
* **[WIP] OSPO case study proposal** | todogroup.org repo
* **Submit a TODO blog post** | todogroup.org repo
* **Submit a feature request** | most used repos
* **Submit a support question** | most used repos
* **[WIP]Request to become an OSPO associate** | ospolandscape repo
* **Report a bug** | most used repos

**Comment by anajsana** [comment]
@vmbrasseur comment: add more documentation (e.g at README.md)

**Comment by anajsana** [comment]
This PR is related to issue: https://github.com/todogroup/governance/issues/111

**Comment by anajsana** [comment]
I've improved the form, making a distinction between what things should cover a new TODO proposal (e.g create a new TODO Working group) and what should be treated as an existing TODO initiative and thus follow the contribution guidelines instead of opening this form: https://github.com/todogroup/todogroup.org#-adding-resources

Please, feel free to check the [PR preview](https://github.com/todogroup/governance/blob/0129a44482831ee48941e71635efd2667db515ee/.github/ISSUE_TEMPLATE/proposals.yml) and add suggestions

**Comment by anajsana** [comment]
This form is no longer needed. An alternative process via GH Discussions and using the proposal tag was approved during the past SC meeting. This is already documented at: https://github.com/todogroup/governance#-file-proposals-by-the-community

**Pull request closed without merging**
